# Generated by Django 5.0.3 on 2024-03-19 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_text', models.CharField(max_length=2000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('short_title', models.CharField(max_length=50)),
                ('edit_date', models.DateTimeField(verbose_name='date edited')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noteit.folder')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noteit.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.CharField(max_length=10000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('edit_date', models.DateTimeField(verbose_name='date edited')),
                ('note_title', models.CharField(max_length=50)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noteit.folder')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noteit.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Long',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_text', models.CharField(max_length=200000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('edit_date', models.DateTimeField(verbose_name='date edited')),
                ('long_title', models.CharField(max_length=50)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noteit.folder')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noteit.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Chirp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chirp_text', models.CharField(max_length=400)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('edit_date', models.DateTimeField(verbose_name='date edited')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noteit.folder')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noteit.tag')),
            ],
        ),
    ]
