# Generated by Django 5.0.3 on 2024-03-21 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='edit_date',
        ),
        migrations.RemoveField(
            model_name='note',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='note',
            name='note_title',
        ),
        migrations.RemoveField(
            model_name='note',
            name='tag',
        ),
    ]
