# Generated by Django 5.0.3 on 2024-03-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteit', '0002_remove_note_edit_date_remove_note_folder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='long',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='short',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='long',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='short',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Chirp',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
        migrations.DeleteModel(
            name='Long',
        ),
        migrations.DeleteModel(
            name='Short',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
