# Generated by Django 5.0.3 on 2024-03-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteit', '0005_tag_alter_note_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_text',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
