# Generated by Django 5.0.3 on 2024-03-21 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteit', '0006_alter_tag_tag_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
