# Generated by Django 5.0.3 on 2024-03-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteit', '0008_remove_note_note_text_note_content_note_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='noteit.tag'),
        ),
    ]
