# Generated by Django 5.0.3 on 2024-04-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteit', '0011_remove_note_pub_date_alter_note_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
