# Generated by Django 5.0.3 on 2024-05-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteit', '0012_note_slug_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
